app:
  database :
    type: mysql
    user: tuzhipeng
    password: Tuzhipeng0@0
    dbName: graduate_design
    address: rm-bp14z26fxx5oy676w125010.mysql.rds.aliyuncs.com
    maxIdle: 500
    maxOpen: 500
  redis:
    address: 47.93.12.71:6379
    network: tcp
    password: 123456
    maxIdle: 2000
    maxActive : 2000
    idleTimeout: 200
  flushAllForTest: false
  rabbitmq:
    username: MjphbXFwLWNuLXRsMzI1MnV3MDAwODpMVEFJNXRGcFZZc0doTGdmUDJWaXhNV1c=
    password: QjRFRDBBOUMzMTU1MTZFMkZEMkZGMUQ3RTg0OTlBRTAwQTAzMkZGQjoxNjE4OTg5MTY2Mzg1
    address: amqp-cn-tl3252uw0008.mq-amqp.cn-shenzhen-429403-a-internal.aliyuncs.com:5672
    virtualHost: graduateDesign
    queenName: secKill
